[package]
name = "angora_common"
version = "1.2.2"
authors = ["sp1npx <spinpx@gmail.com>"]
edition = "2018"

[dependencies]
serde="1.0"
serde_derive = "1.0"
bincode = "1.0"
libc = "0.2"
log = "0.4"
pretty_env_logger = "0.3"
nix = "0.19.0"
lazy_static = "1.1"
strum = "0.22"
strum_macros = "0.22"